version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"  # dacă ai frontend
    directory: "/autosite-frontend"
    schedule:
      interval: "weekly"
