name: Accessibility Audit ♿

on:
  workflow_dispatch:  # rulează manual
  push:
    branches: [main]  # sau ce branch vrei tu

jobs:
  accessibility-audit:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Start frontend server
        run: npm run start &
        shell: bash

      - name: Wait for frontend to boot
        run: timeout 15

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse Accessibility Audit
        run: |
          lighthouse http://localhost:3000 \
            --output html \
            --output-path accessibility-report.html \
            --only-categories=accessibility

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-report
          path: accessibility-report.html
