name: Accessibility Testing ♿

on:
  workflow_dispatch:  # rulează manual
  push:
    branches: [main]  # sau schimbă după preferință

jobs:
  accessibility-audit:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse

      - name: Start frontend server (Next.js)
        run: |
          cd frontend
          npm install
          npm run build
          npm start &
        shell: bash

      - name: Wait for app to boot
        run: timeout 15

      - name: Run Lighthouse audit
        run: |
          lighthouse http://localhost:3000 --output html --output-path accessibility-report.html --only-categories=accessibility

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-report
          path: accessibility-report.html
