name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Type Check
      run: |
        cd frontend
        npm run type-check || echo "Type check not configured yet"
        
    - name: Lint
      run: |
        cd frontend
        npm run lint
        
    - name: Run Tests
      run: |
        cd frontend
        npm run test || echo "Tests not configured yet"
        
    - name: Build
      run: |
        cd frontend
        npm run build
        
    - name: Upload Build
      if: success()
      run: echo "Build completed successfully!"
